

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


springdoc:
  packages-to-scan: onediary.onediary
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui-onediary.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true


server:
  port: 8080
  servlet:
    encoding:
      force: true





spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        dialect.storage_engine: innodb
    show_sql: true

  session:
    store-type: jdbc

  profiles:
    include: oauth

  h2:
    console:
      enabled: true # h2 웹 콘솔 활성화
      path: /h2-console

#  datasource:
#    hikari:
#      username: sa
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
