spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3ede37e3a3b9625b2400ec005083dfe0
            client-secret: MAfpQl5QLPvfZEGSKOOZNFCKtyEqxO8H
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

          naver:
            client-id: 4Gi5VSSNSgD_9kzQTwAa
            client-secret: 9Mj7kvBAAe
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: name, email
            client-name: Naver
#          apple:
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8080/login/oauth2/code/apple
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            scope: name, email
#            client-name: Apple

        provider:
#          apple:
#            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
#            tokenUri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response




## jwt secret key 설정
#jwt.secret: 'b25lZGlhcnktdGVjaC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LW9uZWRpYXJ5LXRlY2gtc3ByaW5nLWJvb3Qtand0LXNlY3JldA0K'
#
## 토큰 관련 secret Key 및 RedirectUri 설정
#app:
##  auth:
##    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
##    tokenExpiry: 1800000
##    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:8080