spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 40219da3deab8b34f69c9f5ea48a62d4
            client-secret: 2IdSt43ekWTZVnQuLm5cVj2pihnVYYTp
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao
          naver:
            client-id: 4Gi5VSSNSgD_9kzQTwAa
            client-secret: 9Mj7kvBAAe
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  token:
    secret-key: [secret-key]
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000