spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 19e6a39dad25f93b4d786c0279afd41a
            redirect-uri: http://localhost:8080/login/oauth2/callback/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao

          naver:
            client-id: kKVbw2JRlUzbgJVWVo_b
            client-secret: THuup8vQz6
            redirect-uri: http://localhost:8080/login/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: name, email
            client-name: naver

#          apple:
#            clientId: { 애플로부터 받은clientId }
#            clientSecret: { 애플로부터 받은 key 파일 }.p8
#            redirectUri: "${backend-rooturl-origin}/login/oauth2/code/apple"
#            authorizationGrantType: authorization_code
#            clientAuthenticationMethod: POST
#            clientName: Apple
#            scope:
#              - name
#              - email


        provider:
#          apple:
#            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
#            tokenUri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response




## jwt secret key 설정
jwt:
  token:
    header: Authorization
    secret: secretonediarykeymerongyerongsecretonediarykeymerongyerongsecretonediarykeymerongyerongsecretonediarykeymerongyerong
    jwtTokenExpiry: 1800000 #30

#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:8080

## JWT token
#token:
#  secret: onediaryserversecretkeysecretsecretsecret
#  access-token-expiration-time: 31536000000
#  refresh-token-expiration-time: 31536000000